# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtcUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('pubadd', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('privkey', models.CharField(blank=True, max_length=64, null=True)),
                ('publickey', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('create_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'btc_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('pubadd', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('privkey', models.CharField(blank=True, max_length=64, null=True)),
                ('publickey', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('create_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eth_user',
                'managed': False,
            },
        ),
    ]
