# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QhAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_pwd', models.CharField(max_length=32)),
                ('access_token', models.CharField(max_length=255)),
                ('last_login_time', models.IntegerField()),
                ('last_login_addr', models.CharField(max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'qh_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhBetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tw_qh_coin', models.IntegerField()),
                ('nper_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('add_time', models.IntegerField()),
                ('is_true', models.IntegerField()),
                ('poundage', models.DecimalField(decimal_places=10, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
            options={
                'db_table': 'qh_betting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhBettingFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('type', models.IntegerField()),
                ('coin_id', models.IntegerField()),
                ('nper_id', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('add_time', models.IntegerField()),
            ],
            options={
                'db_table': 'qh_betting_false',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.IntegerField()),
                ('next_open_time', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=8)),
                ('max_betting_price', models.DecimalField(decimal_places=7, max_digits=15)),
                ('min_betting_price', models.DecimalField(decimal_places=7, max_digits=15)),
                ('max_flat_deviation', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('min_flat_deviation', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('btc_error', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('eth_error', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('open_success', models.IntegerField()),
            ],
            options={
                'db_table': 'qh_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhNper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nper', models.IntegerField()),
                ('open_time', models.IntegerField()),
                ('add_time', models.IntegerField()),
                ('coin_id', models.IntegerField()),
                ('result', models.IntegerField()),
                ('is_current', models.IntegerField()),
                ('up_rate', models.DecimalField(blank=True, decimal_places=18, max_digits=28, null=True)),
                ('down_rate', models.DecimalField(blank=True, decimal_places=18, max_digits=28, null=True)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=18, max_digits=28, null=True)),
                ('result_rate', models.DecimalField(blank=True, decimal_places=18, max_digits=28, null=True)),
                ('stop_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
            ],
            options={
                'db_table': 'qh_nper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhPvuv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('click', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'qh_pvuv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.CharField(max_length=255)),
                ('stop_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('sort', models.IntegerField()),
            ],
            options={
                'db_table': 'qh_queue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nper_id', models.IntegerField()),
                ('coin_id', models.IntegerField()),
                ('exchange_name', models.CharField(max_length=255)),
                ('open_time_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('end_time_price', models.DecimalField(decimal_places=8, max_digits=15)),
            ],
            options={
                'db_table': 'qh_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhResultPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nper_id', models.IntegerField()),
                ('coin_id', models.IntegerField()),
                ('exchange_name', models.CharField(max_length=255)),
                ('open_time_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('end_time_price', models.DecimalField(decimal_places=8, max_digits=15)),
            ],
            options={
                'db_table': 'qh_result_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhRyb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('add_time', models.IntegerField()),
                ('sort', models.IntegerField()),
            ],
            options={
                'db_table': 'qh_ryb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QhTv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinid', models.IntegerField(blank=True, db_column='coinId', null=True)),
                ('exchangename', models.IntegerField(blank=True, db_column='exchangeName', null=True)),
                ('price', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('createtime', models.CharField(blank=True, db_column='createTime', max_length=64, null=True)),
                ('endtime', models.CharField(blank=True, db_column='endTime', max_length=64, null=True)),
            ],
            options={
                'db_table': 'qh_tv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qijia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=64, null=True)),
                ('cointype', models.IntegerField(blank=True, db_column='coinType', null=True)),
                ('name', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=32, null=True)),
                ('inserttime', models.IntegerField(blank=True, db_column='insertTime', null=True)),
            ],
            options={
                'db_table': 'qijia',
                'managed': False,
            },
        ),
    ]
