"""
Django settings for jysAdmin project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#优先在这三个目录下寻找文件
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(0,os.path.join(BASE_DIR,'extra_apps'))
sys.path.insert(0,os.path.join(BASE_DIR,'local_apps'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^dt6qppi+lrqk0+fbjujk@*i$gyo4n0$(f5rmwetm@4ta*hnoi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jys',
    'qhjy',
    'wallet',
    'users',
    'finance',
    'operation',
    'OPS'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jysAdmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jysAdmin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
#数据库联用
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    'db1': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jys',
        'USER': 'qiqi',
        'PASSWORD': 'Qiqi2018_',
        "HOST": "rm-j6c7o95747bp853w0so.mysql.rds.aliyuncs.com",
    },
    'db2': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'qhjy',
        'USER': 'qiqi',
        'PASSWORD': 'Qiqi2018_',
        "HOST": "rm-j6c7o95747bp853w0so.mysql.rds.aliyuncs.com",
    },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wallet',
        'USER': 'qiqi',
        'PASSWORD': 'Qiqi2018_',
        "HOST": "rm-j6c7o95747bp853w0so.mysql.rds.aliyuncs.com",
    },
}
#引入数据库联用的配置文件
DATABASE_ROUTERS = ['jysAdmin.database_router.DatabaseAppsRouter']
#数据库联用的配置
DATABASE_APPS_MAPPING = {
    # example:
    #'app_name':'database_name',
    'jys': 'db1',
    'qhjy': 'db2',
    'wallet':'default'
}
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
#时间改为上海时间
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True
#不使用UTC时间
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
#静态文件存储
STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
#媒体文件存储
MEDIA_URL= '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")